### ISSUE TITLE
I meet some error issues

### ISSUE THREAD

**Issue by Vickywhy** [kai422/CoVOS#3]
Hello,Sorry to bother you.I encountered some issues while running this command" python setup.py build_ext --inplace install"
Can you help me see what the reason is,thank you!(the environment settings pytorch=1.1 cuda=11.3virtual environment python=3.10,annaconda python=3.9)
(CoVOS) WA22201024@bimk-TRX40-DESIGNARE:~/code/CoVOS-main$ python setup.py build_ext --inplace install
running build_ext
building 'mv_warp_func_gpu' extension
Emitting ninja build file /home/WA22201024/code/CoVOS-main/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '/home/WA22201024/code/CoVOS-main/code/CoVOS-main/lib/csrc/mv_warp_func_gpu.cpp', needed by '/home/WA22201024/code/CoVOS-main/build/temp.linux-x86_64-cpython-310/code/CoVOS-main/lib/csrc/mv_warp_func_gpu.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/WA22201024/code/CoVOS-main/setup.py", line 4, in <module>
    setup(
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/WA22201024/anaconda3/envs/CoVOS/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by kai422** [comment]
Hi, it says `mv_warp_func_gpu.cpp` is missing, can you check if the working path is configured correctly?

**Comment by Vickywhy** [comment]
Yes, I changed the path in setup.py
ext_modules=[
        CUDAExtension('mv_warp_func_gpu', [
            'code/CoVOS-main/lib/csrc/mv_warp_func_gpu.cpp',
            'code/CoVOS-main/lib/csrc/mv_warp_func_gpu_kernel.cu',
        ]),
    ],
At the beginning, there was an error message indicating that the pytorch and server cuda versions were not same. Then, I changed the environment configuration file to point to cuda11.3 and ran it again, resulting in above error.And I also checked online and some people said it was a CUDA or PyTorch version issue, but I have already used the same version of PyTorch and changed the CUDA_HOME path to the specified version of CUDA, but it still doesn't work.

**Comment by Vickywhy** [comment]
> Hi, it says `mv_warp_func_gpu.cpp` is missing, can you check if the working path is configured correctly?

Yes, I changed the path in setup.py
ext_modules=[
        CUDAExtension('mv_warp_func_gpu', [
            'code/CoVOS-main/lib/csrc/mv_warp_func_gpu.cpp',
            'code/CoVOS-main/lib/csrc/mv_warp_func_gpu_kernel.cu',
        ]),
    ],
At the beginning, there was an error message indicating that the pytorch and server cuda versions were not same. Then, I changed the environment configuration file to point to cuda11.3 and ran it again, resulting in above error.And I also checked online and some people said it was a CUDA or PyTorch version issue, but I have already used the same version of PyTorch and changed the CUDA_HOME path to the specified version of CUDA, but it still doesn't work.

**Comment by kai422** [comment]
Sorry for the late replay.
This seems to be a problem with the CUDA bindings. Can you install CUDA in a conda environment?

**Comment by Vickywhy** [comment]
> Sorry for the late replay. This seems to be a problem with the CUDA bindings. Can you install CUDA in a conda environment?

I am not a root user, but I should be able to install cuda in a non root mode in my own directory, so do I need to install a specific version of cuda myself？and which version should I install

**Comment by kai422** [comment]
The CUDA is installed by  `conda install pytorch torchvision *cudatoolkit=11.3* -c pytorch`, you can verify the cuda version by nvcc.  When you changed the environment configuration file to point to cuda11.3, make sure to point to the conda version cuda.

**Comment by Vickywhy** [comment]
> The CUDA is installed by `conda install pytorch torchvision *cudatoolkit=11.3* -c pytorch`, you can verify the cuda version by nvcc. When you changed the environment configuration file to point to cuda11.3, make sure to point to the conda version cuda.

yes，I have done conda install pytorch torchvision cudatoolkit=11.3 -c pytorch，and my environment configuration file is set as follows
export PATH=$PATH:/usr/local/cuda-11.3/bin
export CUDA_TOOLKIT_ROOT_DIR="/usr/local/cuda-11.3"
export CUDA_INCLUDE_DIRS="/usr/local/cuda-11.3/include"
export CUDA_CUDART_LIBRARY="/usr/local/cuda-11.3/lib64"
export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH"
export CUDA_HOME=/usr/local/cuda-11.3
this is my nvcc result
![image](https://github.com/kai422/CoVOS/assets/114728720/8c056192-1f0c-4303-b293-6b69042cdb9e)

**Comment by kai422** [comment]
Hi, you should link your cuda to your conda installation. 
please refer to this post: https://stackoverflow.com/questions/72684130/how-to-set-the-cuda-path-in-the-conda-environment

**Comment by Vickywhy** [comment]
Hi，I have reconfigured the environment, which includes cuda nvcc. However, the previously configured environment did not include this package. I have executed this command again and the result shown in the following figure appears. May I ask if the execution was successful？
![image](https://github.com/kai422/CoVOS/assets/114728720/3c60e694-f4c3-42a0-976c-4db87ebf5abd)
